version: "3.9"

services:
  flask-app:
    build: ./app
    container_name: flask-app
    ports:
      - "5000:5000"
    restart: unless-stopped

  ltgm-stack:
    image: ghcr.io/optel-ltgm/ltgm:latest
    container_name: ltgm-stack
    ports:
      - "3000:3000"   # Grafana
      - "9090:9090"   # Prometheus
      - "3100:3100"   # Loki
    restart: unless-stopped